backend:
  image: priyankagupta/backend 
  volumes:
    - ./backend:/usr/src/app
  ports:
    - "4567:4567"
  environment:
    - RACK_ENV=development


frontend:
  image: priyankagupta/frontend
  volumes:
    - ./frontend:/usr/src/app
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=development
  links:
    - backend
